name: PDF CI

on: [push]

jobs:
  pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Render DevOps Resume
        uses: LukaszLapaj/html-to-pdf-action@master
        with:
          htmlFile: ./cv/devops-resume.html
          outputFile: ./build/devops-resume.pdf
          pdfOptions: '{"format": "A4", "margin": {"top": "10mm", "left": "10mm", "right": "10mm", "bottom": "10mm"}}'


      - name: Render PHP Resume
        uses: LukaszLapaj/html-to-pdf-action@master
        with:
          htmlFile: ./cv/php-resume.html
          outputFile: ./build/php-resume.pdf
          pdfOptions: '{"format": "A4", "margin": {"top": "10mm", "left": "10mm", "right": "10mm", "bottom": "10mm"}}'

      - uses: actions/upload-artifact@v4
        with:
          name: PDF files
          path: |
            ./build/devops-resume.pdf
            ./build/php-resume.pdf
          retention-days: 5
          overwrite: true
